name: Build Official Telegram APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1 # Скачиваем только последний коммит, чтобы сэкономить время

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Create local.properties and Inject API Keys
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "TGLIB_APP_ID=${{ secrets.TELEGRAM_API_ID }}" >> local.properties
          echo "TGLIB_APP_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> local.properties
          echo "HOCKEY_APP_HASH=00000000000000000000000000000000" >> local.properties
          echo "FIREBASE_APP_ID=1:000000000000:android:0000000000000000" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Official Telegram Debug APK
        env:
          # Глобально выделяем 6 ГБ памяти на любые фоновые задачи и воркеры Gradle
          GRADLE_OPTS: "-Xmx6g -Xms2g -XX:MaxMetaspaceSize=1g -Dorg.gradle.workers.max=2"
        # Передаем параметр -PabiList=arm64-v8a, чтобы компилировать только под современные телефоны. 
        # Это ускорит сборку в 3 раза и снизит нагрузку на память!
        run: ./gradlew assembleDebug -PabiList=arm64-v8a --stacktrace

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Official-Telegram-Custom
          path: "**/build/outputs/apk/**/*.apk"
